baseURL = "https://relaxed-fermat-8ed881.netlify.app"
title = "Omar Ouederni"
theme = "primaly"
paginate = 5

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Omar Ouederni"
  description = "Networking and Telecommunication engineering student, Flutter developer"
  profile= "images/profile.jpg"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/omaroued"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/ouederni.omar/"

    [[params.social]]
      name = "twitter"
      url = "https://twitter.com/OuederniOmar"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/omarouederni/"

  [[params.social]]
    name = "codecanyon"
    url = "https://codecanyon.net/user/omaroued"


  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

#   Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
